name: "[CI] Build & Test"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Access Token
        run: |
          echo "Secret : ${{ secrets.ACTION_TOKEN }}"

      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build (without check task)
        run: ./gradlew clean build -x check --warning-mode all

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Test with Gradle
        run: ./gradlew test
